export default {
  Mazowieckie: [
    'Warsaw',
    'Radom',
    'Płock',
    'Siedlce',
    'Pruszków',
    'Legionowo',
    'Ostrołęka',
    'Ciechanów',
    'Otwock',
    'Grodzisk Mazowiecki',
    'Mława',
    'Ostrów Mazowiecka',
    'Pułtusk',
    'Gostynin',
    'Garwolin',
    'Kozienice',
    'Grójec',
    'Mińsk Mazowiecki',
    'Żyrardów',
    'Sokołów Podlaski',
    'Płońsk',
    'Sochaczew',
    'Nowy Dwór Mazowiecki',
    'Maków Mazowiecki',
    'Sierpc',
    'Wołomin',
    'Przasnysz',
    'Piaseczno',
    'Węgrów',
    'Ożarów Mazowiecki',
    'Wyszków',
    'Białobrzegi',
    'Szydłowiec',
    'Żuromin',
    'Łosice',
    'Zwoleń',
    'Lipsko',
    'Przysucha'
  ],
  Małopolskie: [
    'Kraków',
    'Tarnów',
    'Oświęcim',
    'Chrzanów',
    'Nowy Targ',
    'Bochnia',
    'Zakopane',
    'Gorlice',
    'Skawina',
    'Wieliczka',
    'Brzesko',
    'Limanowa',
    'Nowy Sącz',
    'Wadowice',
    'Olkusz',
    'Sucha Beskidzka',
    'Myślenice',
    'Dąbrowa Tarnowska',
    'Proszowice',
    'Miechów'
  ],
  Łódzkie: [
    'Łódź',
    'Piotrków Trybunalski',
    'Pabianice',
    'Bełchatów',
    'Skierniewice',
    'Kutno',
    'Sieradz',
    'Łowicz',
    'Opoczno',
    'Łask',
    'Rawa Mazowiecka',
    'Łęczyca',
    'Brzeziny',
    'Zduńska Wola',
    'Tomaszów Mazowiecki',
    'Zgierz',
    'Radomsko',
    'Wieluń',
    'Wieruszów',
    'Pajęczno',
    'Poddębice'
  ],
  Dolnośląskie: [
    'Wrocław',
    'Wałbrzych',
    'Legnica',
    'Jelenia Góra',
    'Głogów',
    'Świdnica',
    'Bolesławiec',
    'Dzierżoniów',
    'Zgorzelec',
    'Bielawa',
    'Kłodzko',
    'Jawor',
    'Złotoryja',
    'Trzebnica',
    'Góra',
    'Lwówek Śląski',
    'Lubin',
    'Oleśnica',
    'Lubań',
    'Oława',
    'Kamienna Góra',
    'Polkowice',
    'Ząbkowice Śląskie',
    'Strzelin',
    'Środa Śląska',
    'Wołów',
    'Milicz'
  ],
  Wielkopolskie: [
    'Poznań',
    'Kalisz',
    'Konin',
    'Gniezno',
    'Leszno',
    'Krotoszyn',
    'Luboń',
    'Jarocin',
    'Wągrowiec',
    'Kościan',
    'Koło',
    'Pleszew',
    'Gostyń',
    'Chodzież',
    'Oborniki',
    'Grodzisk Wielkopolski',
    'Wolsztyn',
    'Ostrów Wielkopolski',
    'Turek',
    'Złotów',
    'Czarnków',
    'Słupca',
    'Piła',
    'Rawicz',
    'Września',
    'Śrem',
    'Kępno',
    'Szamotuły',
    'Środa Wielkopolska',
    'Nowy Tomyśl',
    'Ostrzeszów',
    'Międzychód'
  ],
  Pomorskie: [
    'Gdańsk',
    'Gdynia',
    'Starogard Gdański',
    'Rumia',
    'Kwidzyn',
    'Chojnice',
    'Malbork',
    'Sopot',
    'Lębork',
    'Kościerzyna',
    'Bytów',
    'Człuchów',
    'Tczew',
    'Puck',
    'Wejherowo',
    'Pruszcz Gdański',
    'Słupsk',
    'Kartuzy',
    'Sztum',
    'Nowy Dwór Gdański'
  ],
  Zachodniopomorskie: [
    'Szczecin',
    'Koszalin',
    'Kołobrzeg',
    'Świnoujście',
    'Police',
    'Wałcz',
    'Białogard',
    'Goleniów',
    'Gryfino',
    'Gryfice',
    'Choszczno',
    'Drawsko Pomorskie',
    'Kamień Pomorski',
    'Stargard Szczeciński',
    'Szczecinek',
    'Sławno',
    'Świdwin',
    'Pyrzyce',
    'Myślibórz',
    'Łobez'
  ],
  'Kujawsko-Pomorskie': [
    'Bydgoszcz',
    'Toruń',
    'Włocławek',
    'Grudziądz',
    'Inowrocław',
    'Brodnica',
    'Świecie',
    'Chełmno',
    'Nakło nad Notecią',
    'Rypin',
    'Golub-Dobrzyń',
    'Aleksandrów Kujawski',
    'Wąbrzeźno',
    'Lipno',
    'Radziejów',
    'Żnin',
    'Mogilno',
    'Tuchola',
    'Sępólno Krajeńskie'
  ],
  Lubelskie: [
    'Lublin',
    'Zamość',
    'Chełm',
    'Biała Podlaska',
    'Puławy',
    'Świdnik',
    'Kraśnik',
    'Łuków',
    'Biłgoraj',
    'Lubartów',
    'Łęczna',
    'Krasnystaw',
    'Włodawa',
    'Janów Lubelski',
    'Hrubieszów',
    'Tomaszów Lubelski',
    'Radzyń Podlaski',
    'Ryki',
    'Parczew',
    'Opole Lubelskie'
  ],
  Podlaskie: [
    'Białystok',
    'Suwałki',
    'Łomża',
    'Bielsk Podlaski',
    'Augustów',
    'Grajewo',
    'Hajnówka',
    'Siemiatycze',
    'Kolno',
    'Zambrów',
    'Sejny',
    'Wysokie Mazowieckie',
    'Mońki',
    'Sokółka'
  ],
  Śląskie: [
    'Katowice',
    'Częstochowa',
    'Sosnowiec',
    'Gliwice',
    'Zabrze',
    'Bielsko-Biała',
    'Bytom',
    'Rybnik',
    'Ruda Śląska',
    'Tychy',
    'Dąbrowa Górnicza',
    'Chorzów',
    'Jaworzno',
    'Mysłowice',
    'Tarnowskie Góry',
    'Będzin',
    'Mikołów',
    'Cieszyn',
    'Czeladź',
    'Świętochłowice',
    'Siemianowice Śląskie',
    'Piekary Śląskie',
    'Jastrzębie-Zdrój',
    'Wodzisław Śląski',
    'Żory',
    'Racibórz',
    'Żywiec',
    'Zawiercie',
    'Bieruń',
    'Myszków',
    'Pszczyna',
    'Lubliniec',
    'Kłobuck'
  ],
  Świętokrzyskie: [
    'Kielce',
    'Ostrowiec Świętokrzyski',
    'Starachowice',
    'Sandomierz',
    'Jędrzejów',
    'Kazimierza Wielka',
    'Skarżysko-Kamienna',
    'Końskie',
    'Busko-Zdrój',
    'Staszów',
    'Opatów',
    'Pińczów',
    'Włoszczowa'
  ],
  Podkarpackie: [
    'Rzeszów',
    'Przemyśl',
    'Mielec',
    'Tarnobrzeg',
    'Dębica',
    'Jarosław',
    'Jasło',
    'Brzozów',
    'Łańcut',
    'Przeworsk',
    'Lubaczów',
    'Kolbuszowa',
    'Krosno',
    'Sanok',
    'Stalowa Wola',
    'Leżajsk',
    'Ropczyce',
    'Nisko',
    'Strzyżów',
    'Lesko',
    'Ustrzyki Dolne'
  ],
  'Warmińsko-Mazurskie': [
    'Olsztyn',
    'Elbląg',
    'Ełk',
    'Iława',
    'Giżycko',
    'Kętrzyn',
    'Szczytno',
    'Działdowo',
    'Braniewo',
    'Olecko',
    'Nidzica',
    'Gołdap',
    'Węgorzewo',
    'Nowe Miasto Lubawskie',
    'Ostróda',
    'Mrągowo',
    'Lidzbark Warmiński',
    'Bartoszyce',
    'Pisz'
  ],
  Lubuskie: [
    'Zielona Góra',
    'Gorzów Wielkopolski',
    'Nowa Sól',
    'Żary',
    'Świedbodzin',
    'Międzyrzecz',
    'Wschowa',
    'Krosno Odrzańskie',
    'Żagań',
    'Słubice',
    'Strzelce Krajeńskie',
    'Sulęcin'
  ],
  Opolskie: [
    'Opole',
    'Nysa',
    'Brzeg',
    'Kluczbork',
    'Prudnik',
    'Krapkowice',
    'Głubczyce',
    'Kędzierzyn-Koźle',
    'Strzelce Opolskie',
    'Namysłów',
    'Olesno'
  ]
}
