import Head from 'next/head'
import Image from 'next/image'
import HomeComponent from '../components/home'
import styles from '../styles/Home.module.css'
import HeaderComponent from '../components/header'
import { useRouter } from 'next/router';

import en from '../locales/en'
import vi from '../locales/vi'

export default function Home() {

  const router = useRouter();
  const { locale } = router;
  const t = locale === 'en-US' ? en : vi;

  return (
    <div className={styles.container}>
      <Head>
        <title>Bikini</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;1,100;1,300;1,400&display=swap" />
      </Head>
      <div className={styles.main}>
        <div className='main-header'>
          <HeaderComponent />
        </div>
        <HomeComponent />
      </div>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
